In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import mpld3
#mpld3.enable_notebook()
from mpld3 import plugins
from iex import stock
import requests

#need to really play up the fact that we used a wrapper, which saved us SOOOOO much time
#change BTI to CVX

In [2]:
A = stock('A').chart_table(range='1y')
A = A.rename(columns={'close':'A'})
AAPL = stock('AAPL').chart_table(range='1y')
AAPL = AAPL.rename(columns={'close':'AAPL'})
AMD = stock('AMD').chart_table(range='1y')
AMD = AMD.rename(columns={'close':'AMD'})
ARQL = stock('ARQL').chart_table(range='1y')
ARQL = ARQL.rename(columns={'close':'ARQL'})
AU = stock('AU').chart_table(range='1y')
AU = AU.rename(columns={'close':'AU'})
BHP = stock('BHP').chart_table(range='1y')
BHP = BHP.rename(columns={'close':'BHP'})
BLIN  = stock('BLIN').chart_table(range='1y')
BLIN = BLIN.rename(columns={'close':'BLIN'})
BOSC = stock('BOSC').chart_table(range='1y')
BOSC = BOSC.rename(columns={'close':'BOSC'})
BP = stock('BP').chart_table(range='1y')
BP = BP.rename(columns={'close':'BP'})
BTI= stock('BTI').chart_table(range='1y')
BTI = BTI.rename(columns={'close':'BTI'})

https://api.iextrading.com/1.0/stock/A/chart/1y
https://api.iextrading.com/1.0/stock/AAPL/chart/1y
https://api.iextrading.com/1.0/stock/AMD/chart/1y
https://api.iextrading.com/1.0/stock/ARQL/chart/1y
https://api.iextrading.com/1.0/stock/AU/chart/1y
https://api.iextrading.com/1.0/stock/BHP/chart/1y
https://api.iextrading.com/1.0/stock/BLIN/chart/1y
https://api.iextrading.com/1.0/stock/BOSC/chart/1y
https://api.iextrading.com/1.0/stock/BP/chart/1y
https://api.iextrading.com/1.0/stock/BTI/chart/1y

In [3]:
df_1y = A[['date','A']]
df_1y = df_1y.join(AAPL['AAPL'])
df_1y = df_1y.join(AMD['AMD'])
df_1y = df_1y.join(ARQL['ARQL'])
df_1y = df_1y.join(AU['AU'])
df_1y = df_1y.join(BHP['BHP'])
df_1y = df_1y.join(BLIN['BLIN'])
df_1y = df_1y.join(BOSC['BOSC'])
df_1y = df_1y.join(BP['BP'])
df_1y = df_1y.join(BTI['BTI'])
df_1y

,date,A,AAPL,AMD,ARQL,AU,BHP,BLIN,BOSC,BP,BTI
0,2017-07-10,59.3290,142.8395,13.81,1.29,9.7484,36.0286,2.8995,1.9000,32.3663,63.1093
1,2017-07-11,59.2695,143.3023,13.89,1.29,9.8179,36.5359,3.0000,1.9000,32.3946,63.1663
2,2017-07-12,60.1912,143.5091,14.29,1.33,9.9571,36.8231,2.8500,2.0800,32.8755,64.7715
3,2017-07-13,60.6472,145.5080,13.53,1.30,9.7384,36.9858,2.9500,2.0300,32.7340,64.8380
4,2017-07-14,60.9742,146.7586,13.92,1.31,9.7484,37.7133,2.9375,2.0600,32.9509,65.8069
5,2017-07-17,61.0040,147.2706,13.80,1.31,9.6788,37.9430,2.9505,2.0000,32.9226,65.5124
6,2017-07-18,60.6670,147.7827,13.48,1.27,9.7384,37.7420,2.7505,2.0071,32.8377,64.7051
7,2017-07-19,60.8355,148.7083,13.55,1.27,9.5993,38.1057,2.8500,2.0000,33.0263,65.9209
8,2017-07-20,60.4390,148.0387,13.80,1.28,9.4900,37.5314,2.8500,2.0500,33.0923,66.4908
9,2017-07-21,60.8256,147.9698,13.88,1.28,9.6192,37.1294,2.9250,1.9900,32.6963,67.9631
10,2017-07-24,60.9544,149.7619,14.16,1.23,9.3906,37.2251,2.7805,1.9800,32.4889,65.7784
11,2017-07-25,60.0029,150.4019,14.11,1.21,9.5198,38.4886,3.1000,2.0000,32.9037,65.7404
12,2017-07-26,59.1902,151.1109,14.76,1.23,9.7981,39.0151,3.1181,1.9900,32.8472,65.2560
13,2017-07-27,59.3785,148.2553,14.12,1.22,9.6788,39.0533,3.1034,2.0000,32.9886,61.6750
14,2017-07-28,59.5470,147.2115,13.95,1.16,10.0664,39.3788,2.8907,1.9958,33.1489,61.6750
15,2017-07-31,59.2596,146.4533,13.61,1.16,9.9571,39.8765,3.1000,2.0500,33.1300,59.3858
16,2017-08-01,59.4083,156.1624,13.71,1.14,9.8875,39.4458,2.8300,2.0100,34.3179,62.1119
17,2017-08-02,59.6659,154.7346,13.37,1.11,9.5198,39.3979,2.7400,1.9600,34.3179,60.8391
18,2017-08-03,59.8344,153.1886,13.24,1.10,9.2813,39.0533,2.4400,1.8850,34.0728,61.9219
19,2017-08-04,59.5966,153.9961,13.12,1.12,9.0826,39.4458,2.3000,1.8700,34.2519,62.5679
20,2017-08-07,60.3300,156.3790,13.43,1.10,9.0428,40.1924,2.2200,1.9100,34.6479,62.1119
21,2017-08-08,59.6065,157.6296,13.11,1.08,9.1323,39.6947,2.2000,1.8900,34.4499,60.8676
22,2017-08-09,59.1506,158.5946,12.83,1.00,9.1720,39.5894,2.1200,1.9800,34.6560,61.2475
23,2017-08-10,58.0504,153.5431,12.12,1.00,9.5198,38.8810,2.1300,1.9900,33.9947,59.7277
24,2017-08-11,58.8037,155.6784,12.23,1.03,9.6490,38.6226,2.2300,1.8600,33.4867,59.7562
25,2017-08-14,59.0911,158.0213,12.76,1.05,9.7086,38.7279,2.3009,1.8900,33.2376,59.6613
26,2017-08-15,58.8532,159.7513,13.02,1.05,9.6093,38.3546,2.4800,1.9900,33.1321,60.1837
27,2017-08-16,61.5887,159.1087,12.63,1.05,9.7782,39.4075,2.4400,1.9400,32.8638,60.4428
28,2017-08-17,60.3201,156.0541,12.34,1.05,9.7682,38.7279,2.4200,1.8600,32.6817,59.2265
29,2017-08-18,60.7066,155.6982,12.37,1.03,9.7583,38.6705,2.6000,1.8300,32.7392,58.6955
...,...,...,...,...,...,...,...,...,...,...,...
223,2018-05-29,61.7010,187.9000,13.36,5.00,8.4600,48.1400,1.3700,2.4000,44.5400,49.6056
224,2018-05-30,62.5390,187.5000,13.82,4.73,8.5900,49.4300,1.3940,2.4975,45.7100,50.1283
225,2018-05-31,61.7708,186.8700,13.73,4.85,8.6200,49.7800,1.3800,2.4900,45.8200,50.4932
226,2018-06-01,62.6288,190.2400,14.40,4.96,8.7000,50.2400,1.4300,2.4500,45.9200,50.0691
227,2018-06-04,63.2273,191.8300,14.85,4.89,8.6800,50.1900,1.3500,2.3742,45.9600,50.0001
228,2018-06-05,63.3670,193.3100,14.85,5.20,8.7700,50.5600,1.2379,2.3600,46.2900,49.0040
229,2018-06-06,65.0330,193.9800,15.67,5.78,8.6400,51.9500,1.2100,2.3700,46.2800,49.0040
230,2018-06-07,65.0729,193.4600,14.89,5.78,8.5800,51.7600,1.2100,2.3500,47.2000,48.1756
231,2018-06-08,65.5717,191.7000,15.25,5.33,8.6500,51.6700,1.2700,2.3400,47.0400,48.6293
232,2018-06-11,65.9707,191.2300,15.73,5.28,8.5800,51.8300,1.2100,2.2746,47.1200,49.6746
233,2018-06-12,66.1602,192.2800,15.85,5.18,8.5800,51.1400,1.2700,2.2100,46.1200,48.6194
234,2018-06-13,66.1004,190.7000,16.32,5.51,8.6400,50.6900,1.2000,2.2804,46.0100,48.8167
235,2018-06-14,66.1503,190.8000,16.25,5.31,8.6800,50.3600,1.1900,2.2400,46.4400,48.9153
236,2018-06-15,65.9707,188.8400,16.34,4.99,8.1500,48.7000,1.2300,2.2500,45.1300,48.6589
237,2018-06-18,64.8135,188.7400,17.11,5.00,8.1200,48.9700,1.2200,2.2300,45.3500,47.6727
238,2018-06-19,63.3670,185.6900,16.69,4.88,8.1000,47.6400,1.2800,2.2600,45.1500,47.8798
239,2018-06-20,62.6387,186.5000,16.52,4.74,8.2200,47.7700,1.2310,2.2700,44.7600,49.1520
240,2018-06-21,62.8881,185.4600,15.65,4.69,8.2300,47.8800,1.2310,2.2400,44.1600,49.8028
241,2018-06-22,62.6387,184.9200,15.80,4.76,8.2600,48.9300,1.2307,2.1200,45.7800,50.8186
242,2018-06-25,61.0526,182.1700,15.11,5.09,8.2300,47.6400,1.2300,2.2500,44.2400,49.6648
243,2018-06-26,61.8307,184.4300,15.50,5.37,8.1800,48.8300,1.2100,2.2400,44.8900,48.9547
244,2018-06-27,60.9927,184.1600,14.97,5.21,7.9700,49.3100,1.1700,2.2737,45.4400,48.5208
245,2018-06-28,61.1424,185.5000,15.31,5.04,7.8600,50.0200,1.1700,2.3100,45.6700,50.7500
246,2018-06-29,61.6910,185.1100,14.99,5.53,8.2100,50.0100,1.1400,2.3200,45.6600,50.4500
247,2018-07-02,61.4700,187.1800,15.16,5.77,8.2200,48.5700,1.1200,2.3000,45.2000,50.0800
248,2018-07-03,61.2500,183.9200,15.00,5.76,8.2900,48.7100,1.1400,2.4300,45.9000,51.1800
249,2018-07-05,61.8000,185.4000,15.50,5.67,8.5100,48.6900,1.1500,2.5000,46.0000,51.6900
250,2018-07-06,62.2900,187.9700,16.36,6.81,8.7100,49.5800,1.2690,2.4700,45.9400,51.7800
251,2018-07-09,63.1200,190.5800,16.61,6.69,8.7300,50.8300,1.3100,2.4168,46.6000,52.2100
252,2018-07-10,63.6700,190.3500,16.55,6.15,8.8600,51.1800,2.3000,NaN,47.0500,52.2500

In [4]:
A_2 = stock('A').chart_table(range='2y')
A_2 = A_2.rename(columns={'close':'A'})
AAPL_2 = stock('AAPL').chart_table(range='2y')
AAPL_2 = AAPL_2.rename(columns={'close':'AAPL'})
AMD_2 = stock('AMD').chart_table(range='2y')
AMD_2 = AMD_2.rename(columns={'close':'AMD'})
ARQL_2 = stock('ARQL').chart_table(range='2y')
ARQL_2 = ARQL_2.rename(columns={'close':'ARQL'})
AU_2 = stock('AU').chart_table(range='2y')
AU_2 = AU_2.rename(columns={'close':'AU'})
BHP_2 = stock('BHP').chart_table(range='2y')
BHP_2 = BHP_2.rename(columns={'close':'BHP'})
BLIN_2  = stock('BLIN').chart_table(range='2y')
BLIN_2 = BLIN_2.rename(columns={'close':'BLIN'})
BOSC_2 = stock('BOSC').chart_table(range='2y')
BOSC_2 = BOSC_2.rename(columns={'close':'BOSC'})
BP_2 = stock('BP').chart_table(range='2y')
BP_2 = BP_2.rename(columns={'close':'BP'})
BTI_2 = stock('BTI').chart_table(range='2y')
BTI_2 = BTI_2.rename(columns={'close':'BTI'})

https://api.iextrading.com/1.0/stock/A/chart/2y
https://api.iextrading.com/1.0/stock/AAPL/chart/2y
https://api.iextrading.com/1.0/stock/AMD/chart/2y
https://api.iextrading.com/1.0/stock/ARQL/chart/2y
https://api.iextrading.com/1.0/stock/AU/chart/2y
https://api.iextrading.com/1.0/stock/BHP/chart/2y
https://api.iextrading.com/1.0/stock/BLIN/chart/2y
https://api.iextrading.com/1.0/stock/BOSC/chart/2y
https://api.iextrading.com/1.0/stock/BP/chart/2y
https://api.iextrading.com/1.0/stock/BTI/chart/2y

In [5]:
df_2y = A_2[['date','A']]
df_2y = df_2y.join(AAPL_2['AAPL'])
df_2y = df_2y.join(AMD_2['AMD'])
df_2y = df_2y.join(ARQL_2['ARQL'])
df_2y = df_2y.join(AU_2['AU'])
df_2y = df_2y.join(BHP_2['BHP'])
df_2y = df_2y.join(BLIN_2['BLIN'])
df_2y = df_2y.join(BOSC_2['BOSC'])
df_2y = df_2y.join(BP_2['BP'])
df_2y = df_2y.join(BTI_2['BTI'])

In [6]:
A_5 = stock('A').chart_table(range='5y')
A_5 = A_5.rename(columns={'close':'A'})
AAPL_5 = stock('AAPL').chart_table(range='5y')
AAPL_5 = AAPL_5.rename(columns={'close':'AAPL'})
AMD_5 = stock('AMD').chart_table(range='5y')
AMD_5 = AMD_5.rename(columns={'close':'AMD'})
ARQL_5 = stock('ARQL').chart_table(range='5y')
ARQL_5 = ARQL_5.rename(columns={'close':'ARQL'})
AU_5 = stock('AU').chart_table(range='5y')
AU_5 = AU_5.rename(columns={'close':'AU'})
BHP_5 = stock('BHP').chart_table(range='5y')
BHP_5 = BHP_5.rename(columns={'close':'BHP'})
BLIN_5  = stock('BLIN').chart_table(range='5y')
BLIN_5 = BLIN_5.rename(columns={'close':'BLIN'})
BOSC_5 = stock('BOSC').chart_table(range='5y')
BOSC_5 = BOSC_5.rename(columns={'close':'BOSC'})
BP_5 = stock('BP').chart_table(range='5y')
BP_5 = BP_5.rename(columns={'close':'BP'})
BTI_5 = stock('BTI').chart_table(range='5y')
BTI_5 = BTI_5.rename(columns={'close':'CVX'})

https://api.iextrading.com/1.0/stock/A/chart/5y
https://api.iextrading.com/1.0/stock/AAPL/chart/5y
https://api.iextrading.com/1.0/stock/AMD/chart/5y
https://api.iextrading.com/1.0/stock/ARQL/chart/5y
https://api.iextrading.com/1.0/stock/AU/chart/5y
https://api.iextrading.com/1.0/stock/BHP/chart/5y
https://api.iextrading.com/1.0/stock/BLIN/chart/5y
https://api.iextrading.com/1.0/stock/BOSC/chart/5y
https://api.iextrading.com/1.0/stock/BP/chart/5y
https://api.iextrading.com/1.0/stock/BTI/chart/5y

In [7]:
df_5y = A_5[['date','A']]
df_5y = df_5y.join(AAPL_5['AAPL'])
df_5y = df_5y.join(AMD_5['AMD'])
df_5y = df_5y.join(ARQL_5['ARQL'])
df_5y = df_5y.join(AU_5['AU'])
df_5y = df_5y.join(BHP_5['BHP'])
df_5y = df_5y.join(BLIN_5['BLIN'])
df_5y = df_5y.join(BOSC_5['BOSC'])
df_5y = df_5y.join(BP_5['BP'])
df_5y = df_5y.join(BTI_5['CVX'])

In [8]:
df_1y_date = df_1y['date'].values.tolist()
df_1y_a = df_1y['A'].values.tolist()
df_1y_aapl = df_1y['AAPL'].values.tolist()
df_1y_amd = df_1y['AMD'].values.tolist()
df_1y_arql = df_1y['ARQL'].values.tolist()
df_1y_au = df_1y['AU'].values.tolist()
df_1y_bhp = df_1y['BHP'].values.tolist()
df_1y_blin = df_1y['BLIN'].values.tolist()
df_1y_bosc = df_1y['BOSC'].values.tolist()
df_1y_bp = df_1y['BP'].values.tolist()
df_1y_bti = df_1y['CVX'].values.tolist()

In [ ]:
fig, ax = plt.subplots()
ax.set_title('Stocks')
plt.plot(df_1y['date'].tolist(), df_1y_a)
plt.plot(df_1y['date'].tolist(), df_1y_aapl)
plt.plot(df_1y['date'].tolist(), df_1y_amd)
plt.plot(df_1y['date'].tolist(), df_1y_arql)
plt.plot(df_1y['date'].tolist(), df_1y_au)
plt.plot(df_1y['date'].tolist(), df_1y_bhp)
plt.plot(df_1y['date'].tolist(), df_1y_blin)
plt.plot(df_1y['date'].tolist(), df_1y_bosc)
plt.plot(df_1y['date'].tolist(), df_1y_bp)
plt.plot(df_1y['date'].tolist(), df_1y_bti)

ax.set_xlabel('Date')
ax.set_ylabel('Stock Price')
labels = ["Day of year {0}".format(i) for i in range(366)]

handles, labels = ax.get_legend_handles_labels() # return lines and labels
interactive_legend = plugins.InteractiveLegendPlugin(zip(handles,
                                                         ax.collections),
                                                     labels,
                                                     alpha_unsel=0.5,
                                                     alpha_over=1.5, 
                                                     start_visible=True)
plugins.connect(fig, interactive_legend)

#tooltip = plugins.PointLabelTooltip(points, labels)
#plugins.connect(fig, tooltip)

mpld3.show()

Note: if you're in the IPython notebook, mpld3.show() is not the best command
      to use. Consider using mpld3.display(), or mpld3.enable_notebook().
      See more information at http://mpld3.github.io/quickstart.html .

You must interrupt the kernel to end this command

Serving to http://127.0.0.1:8889/    [Ctrl-C to exit]

127.0.0.1 - - [11/Jul/2018 20:59:20] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [11/Jul/2018 20:59:20] "GET /d3.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Jul/2018 20:59:20] "GET /mpld3.js HTTP/1.1" 200 -

In [ ]:
df_1y